name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: Darkness1853
          outputs: |
            dist/github-snake.svg
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate snake files"
          branch: output
          file_pattern: dist/*
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          skip_checkout: true 
